name: Welcome New Contributors

on:
  branches:
      - main
  pull_request_target:
      types: [ opened ]

jobs:
  # Comments on a pull request when the author is a new contributor.
  post-welcome-message:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/welcome-action@8dbbac2540d155744c90e4e37da6b05ffc9c5e2c # v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          FIRST_PR_COMMENT:
            Hi @{{ author }}! ðŸ‘‹
            Thank you for your contribution to ClassicPress Snippets! ðŸ’–
            It looks like this is your first pull request. We appreciate and value your contribution!

            Please read our [contribution guide](CONTRIBUTING.md) to find out how you can be more involved.

			Thank you,
			Laurence, ClassicPress Snippets Team.
